caparu/urls.py
from django.urls import path
from .views import caparu_view

app_name = 'caparu'

urlpatterns = [
    path('', caparu_view, name='caparu-view'),
]

cv/urls.py
from django.urls import path
from .views import cv_view

app_name = 'cv'

urlpatterns = [
    path('', cv_view, name='cv-view'),
]

dbt/urls.py
from django.urls import path
from .views import dbt_view

app_name = 'dbt'

urlpatterns = [
    path('', dbt_view, name='dbt-view'),
]

portfolio/urls.py
from django.urls import path
from .views import portfolio_view

app_name = 'portfolio'

urlpatterns = [
    path('', portfolio_view, name='portfolio-view'),
]

tali/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('cv/', include('cv.urls', namespace='cv')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('caparu/', include('caparu.urls', namespace='caparu')),
    path('tftsd/', include('tftsd.urls', namespace='tftsd')),
    path('dbt/', include('dbt.urls', namespace='dbt')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tftsd/urls.py
from django.urls import path
from .views import tftsd_view

app_name = 'tftsd'

urlpatterns = [
    path('', tftsd_view, name='tftsd-view'),
]

caparu/models.py
from django.db import models

# Create your models here.

cv/models.py
from django.db import models

# Create your models here.

dbt/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

# Create your models here.

tftsd/models.py
from django.db import models

# Create your models here.

caparu/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

def caparu_view(request):
    return render(request, 'caparu/caparu.html')

cv/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

def cv_view(request):
    return render(request, 'cv/cv.html')

dbt/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

def dbt_view(request):
    return render(request, 'dbt/dbt.html')

portfolio/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView


def portfolio_view(request):
    return render(request, 'portfolio/portfolio.html')

tali/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home_view(request):
    user = request.user
    hello = 'Hello world'

    context = {
        'user': user,
        'hello' : hello,
    }
    return render(request, 'main/home.html', context)
    # return HttpResponse('Hello world')

tftsd/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView

def tftsd_view(request):
    return render(request, 'tftsd/tftsd.html')

caparu/templates/caparu/caparu.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Caparu
{% endblock title %}

{% block content %}
<!-- <div class="iconwrapper">
    <a href="https://www.facebook.com/rafi.reyesespinosa/">
    <i class="fab fa-facebook"></i>
  </a>
    <a href="https://www.instagram.com/tales.from.the.sexdungeon/">
    <i class="fab fa-instagram"></i>
  </a>
</div>
</nav>
</div>

Image cover background and headline ontop -->
<header class="header"> <img src="{% static 'images/caparu.jpg' %}" alt="">
</header>
<!-- <h1 class="cover">Caparu</h1> -->










{% endblock content %}

cv/templates/cv/cv.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
C.V.
{% endblock title %}

{% block content %}





<!-- <div class="container">
    <div class="row">
        <div class="col-4"><img src="{% static 'images/tri.png' %}" alt=""></div>
        <div class="col-8">
            <h1>Tali Rozenman Ismael</h1>
            <h2>Industial Designer | Full-Stack Developer</h2>
        </div>
    </div>
</div> -->

<div class="clearfix">
    <img src="{% static 'images/tri.png' %}" id="tri" class="col-3 float-md-start ms-md-3" alt="...">
    <h1 class="mt-10" >Tali Rozenman Ismael</h1>
    <h2>Industial Designer | Full-Stack Developer</h2>
    <p>Tel Aviv | +972549112332 | rozenlady.t@gmail.com</p>
    <p>LinkedIn: <a href="https://www.linkedin.com/in/rozenlady/">Rozenlady</a> Github: <a href="https://github.com/rozenlady">Rozenlady</a>
    </p>
    
</div>



<div class="container">
    <div class="row">
      <div class="col-md-4 float-md-start mb-2 ms-md-3">
          <h2>In a few words... </h2>
      </div>
      <p>
        As part of my next professional step I see myself building a community and being part of an impactful business. I want to create or collaborate in meaningful projects that allow myself and others to thrive. My areas of interests are innovation within environmental conservancy, sustainability, education, and nutrition & food tech. I find these to be key for development and economic growth worldwide. 
      </p>
    </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-md-4 float-md-start mb-2 ms-md-3">
          <h2>Skills</h2>
      </div>
      <ul>
          <li>Python, SQL, Flask, Django, JavaScript, HTML, CSS</li>
          <li>Fluent: English, Spanish; Intermediate: Portuguese Brazil; Intermediate:  Hebrew </li>
          <li>3D Design: Rhinosceros 3D, Solid Works, Inventor, SketchUp</li>
          <li>Graphic Design: InDesign, Photoshop, Illustrator;  Video: Adobe Premier</li> 
      </ul>
    </div>
</div>

<div class="container">
    <div class="row">
      <div class="col-md-4 float-md-start mb-2 ms-md-3">
          <h2>Technical Projects</h2>
      </div>
      <div class="container">
          <div class="row">
                <div class="col-sm-6">
                  <h3><a href="https://github.com/rozenlady/Tales-from-the-S.D.">TALES FROM THE S.D.</a></h3>
                        <ul>
                            <li>Website for Community Building Events.</li>
                            <li>JQuery for the calendar to set dates & send emails.</li>
                            <li>Responsive Design using HTML, CSS and JavaScript</li>
                            <li>Graphic Design: InDesign, Photoshop, Illustrator;  Video: Adobe Premier</li> 
                        </ul>
                </div>
                <div class="col-sm-6">
                <h3><a href="https://github.com/rozenlady/NoLedge">No Ledge</a></h3></h3>
                <ul>
                    <li>Search Engine in which only verified users can post</li>
                    <li>Created 3 models for different type of users</li>
                    <li>Used SQL database to organise selected data per user</li>
                </ul>
            </div>
        </div>  
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4 float-md-start mb-2 ms-md-3">
            <h2>Education</h2>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-7">
                <p>Developers Institute Full Stack Web Development Bootcamp </p>
            </div>
            <div class="col-2">
                <p>Israel</p>
            </div>
            <div class="col-3">
                <p>2020-2021</p>
            </div>
        </div>

        
        <div class="row">
            <div class="col-7">
                <p>Universidad Veritas B.A. Industrial Design</p>
            </div>
            <div class="col-2">
                <p>Costa Rica</p>
            </div>
            <div class="col-3">
                <p>2012-2015</p>
            </div>
        </div>
        <div class="row">
            <div class="col-7">
                <p>Daner Luna School of Fashion Patternmaking and Sewing Technique Diploma</p>
            </div>
            <div class="col-2">
                <p>Bolivia</p>
            </div>
            <div class="col-3">
                <p>2011</p>
            </div>
        </div>
        <div class="row">
            <div class="col-7">
                <p>Instituto Tecnologico de Monterrey</p>
            </div>
            <div class="col-2">
                <p>Mexico</p>
            </div>
            <div class="col-3">
                <p>2010</p>
            </div>
        </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4 float-md-start mt-2 mb-2 ms-md-3">
            <h2>Experience</h2>
        </div>
    </div> 

    <div class="row">
        <div class="container">
            <div class="row">
                <div class=" float-md mb-1 ms-md-1">
                    <h4>Freelancer</h4>
                    <p>Sep 2019 – Present</p>
                </div>
            </div>
            <div class="row">
                <h5>Eatsane by a1cfoods, Graphic Designer and Marketing, Israel & USA </h5>
            </div>
            <div class="row">
                <ul>
                    <li>Facebook Art, Bundles, Packaging, Labels, Videos Translations</li>

                </ul>
            </div>

            <div class="row">
                <h5>Energycenter, Graphic Designer, Bolivia</h5>
            </div>
            <div class="row">
                <ul>
                    <li>Facebook Art and Bundles</li>

                </ul>
            </div>


        </div>
    </div>
    

    <div class="row">
        <div class="container">
            <div class="row">
                <div class=" float-md-start mb-1 mt-2 ms-md-1">
                    <h4>Morazi</h4>
                    <p>Mar 2019 – Feb 2020</p>
                </div>
            </div>
            <div class="row">
                <ul>
                    <li>Created Facebook campaigns in English and Spanish</li>
                    <li>Proofread, edited and approved body of content for social media campaigns in English and Spanish.</li>
                    <li>Developed a strategy that optimized the creation, design and duplication of content that increased CTR</li>
                    <li>Created networks to collaborate with potential sources of content Created Facebook campaigns in English and Spanish</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="container">
            <div class="row">
                <div class="float-md-start mb-1 mt-2 ms-md-1">
                    <h4>The Poli House Brown Hotels, Guest Relations Manager, Tel Aviv</h4>
                    <p>Jul 2017 – April 2018</p>
                </div>
            </div>
            <div class="row">
                <ul>
                    <li>Hired, trained, and managed team members</li>
                    <li>Created a guest satisfaction flowchart based on the needs of guests, creating checklists for staff that improved guest experience</li>
                    <li>Developed a strategy that optimized the creation, design and duplication of content that increased CTR</li>
                    <li>Designed added value products for guest retention and satisfaction. These products increased use of the hotel’s facilities</li>
                    <li>Designed and created a Google Platform to help guests plan their own itineraries. </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="container">
            <div class="row">
                <div class="float-md-start mb-1 mt-2 ms-md-1">
                    <h4>Usbepower, Industrial Design Intern, Tel Aviv</h4>
                    <p>Jan – Jun 2017</p>
                </div>
            </div>
            <div class="row">
                <ul>
                    <li>Research and benchmarking R&D</li>
                    <li>Sketching and modeling: designed and tested ergonomic solutions to standardize the American version of the company’s product </li>
                    <li>Designed point of purchase (POP) materials, exhibition stands, store display furniture, catalogues, and postals.</li>
                </ul>
            </div>
        </div>
    </div>
    

    <div class="row">
        <div class="container">
            <div class="row">
                <div class="float-md-start mb-1 mt-2 ms-md-1">
                    <h4>MADISA, Industrial Design, Santa Cruz, Bolivia</h4>
                    <p>Aug  2015 – Dec 2017</p>
                </div>
            </div>
            <div class="row">
                <ul>
                    <li>Benchmarked for food design and labels as part of the R&D team.</li>
                    <li>Packaging and label design </li>
                    <li>POP for multiple products: catalogues, banners, exhibition stands, events, Facebook arts, and more.</li>
                    <li>Content management of Facebook ads and labels</li>
                    <li>As part of this marketing team, I was in charge of rebranding a struggling product that wasn’t succeeding in the market due to ineffective labeling. After the relaunch of the product, sales increased by 600%.
                        Collaborated on the creation of the marketing structure for all product lines (Food and Confectionery, Energy and Lighting, Home Appliances, and Food Manufacturing), targeting both audiences B2B and B2C.</li>
                </ul>
            </div>
        </div>
    </div>

    
     
    










                                                      	           	   	 
    
    
    
     
    
    




</div>
        




{% endblock content %}

dbt/templates/dbt/dbt.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
don't be trashy!
{% endblock title %}

{% block content %}



<section class="center">
    <div class="container" margin="auto">
        <div class="col-12" class="row">
            <div justify-content="center">
                <h2>Don't Be Trashy</h2>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <!--manual navigation end-->

                <div class="slider">
                    <div class="slides">
                    <!--radio buttons start-->
                    <input type="radio" name="radio-btn" id="radio1">
                    <input type="radio" name="radio-btn" id="radio2">
                    <input type="radio" name="radio-btn" id="radio3">
                    <input type="radio" name="radio-btn" id="radio4">
                    <!--radio buttons end-->
                    <!--slide images start-->
                    <div class="slide first">
                        <img src="{% static 'images/dbt/bioCo/1.png' %}" alt="">
                    </div>
                    <div class="slide">
                        <img src="{% static 'images/dbt/bioCo/2.png' %}" alt="">
                    </div>
                    <div class="slide">
                        <img src="{% static 'images/dbt/bioCo/3.png' %}" alt="">
                    </div>
                    <div class="slide">
                        <img src="{% static 'images/dbt/bioCo/4.png' %}" alt="">
                    </div>
                    <div class="slide">
                        <img src="{% static 'images/dbt/bioCo/5.png' %}" alt="">
                    </div>
      
                    <!--slide images end-->
                
                
                    <!--automatic navigation start-->
                    <div class="navigation-auto">
                        <div class="auto-btn1"></div>
                        <div class="auto-btn2"></div>
                        <div class="auto-btn3"></div>
                        <div class="auto-btn4"></div>
                    </div>
                    <!--automatic navigation end-->
                    </div>
                    <!--manual navigation start-->
                    <div class="navigation-manual">
                    <label for="radio1" class="manual-btn"></label>
                    <label for="radio2" class="manual-btn"></label>
                    <label for="radio3" class="manual-btn"></label>
                    <label for="radio4" class="manual-btn"></label>
                    </div>
                
                <!--image slider end-->
            </div>
            
        </div>
    </div>

</section>



<script type="text/javascript">
var counter = 1;
setInterval(function(){
document.getElementById('radio' + counter).checked = true;
counter++;
if(counter > 5){
  counter = 1;
}
}, 2500);
</script>










{% endblock content %}

portfolio/templates/portfolio/portfolio.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Portfolio
{% endblock title %}

{% block content %}


    <section class="center">
            <div class="portfolio">
              <img src="{% static 'images/portfolio/1.jpg' %}">
              <img src="{% static 'images/portfolio/2.jpg' %}">
              <img src="{% static 'images/portfolio/4.jpg' %}">
              <img src="{% static 'images/portfolio/5.jpg' %}">
              <img src="{% static 'images/portfolio/6.jpg' %}">
              <img src="{% static 'images/portfolio/7.jpg' %}">
              <img src="{% static 'images/portfolio/8.jpg' %}">
              <img src="{% static 'images/portfolio/9.jpg' %}">
              <img src="{% static 'images/portfolio/10.jpg' %}">
              <img src="{% static 'images/portfolio/11.jpg' %}">
              <img src="{% static 'images/portfolio/12.jpg' %}">
              <img src="{% static 'images/portfolio/13.jpg' %}">
              <img src="{% static 'images/portfolio/14.jpg' %}">
              <img src="{% static 'images/portfolio/15.jpg' %}">
              <img src="{% static 'images/portfolio/16.jpg' %}">
              <img src="{% static 'images/portfolio/17.jpg' %}">


            </div>
    </section>



  <script type="text/javascript">
    const slideshowImages = document.querySelectorAll(".portfolio img");

    const nextImageDelay = 1500;
    let currentImageCounter = 0; // setting a variable to keep track of the current image (slide)

    // slideshowImages[currentImageCounter].style.display = "block";
    slideshowImages[currentImageCounter].style.opacity = 1;

    setInterval(nextImage, nextImageDelay);

    function nextImage() {
    // slideshowImages[currentImageCounter].style.display = "none";
    slideshowImages[currentImageCounter].style.opacity = 0;

    currentImageCounter = (currentImageCounter+1) % slideshowImages.length;

    // slideshowImages[currentImageCounter].style.display = "block";
    slideshowImages[currentImageCounter].style.opacity = 1;
    }
  </script>





{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no" />
        <title>Tali Rozenman Ismael</title>
        <link rel="stylesheet" type="text/css" href={% static 'style.css' %}/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


    </head>
    <body>
        {% include 'main/navbar.html' %}
        <div class="ui container">
          {% block content %}
          {% endblock content %}
        </div>

    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    


    </body>
</html>


    <!-- ☰ -->

templates/base4.html
{% load static %}
{% url 'cv:cv-view' as path_to_cv_view %}
{% url 'portfolio:portfolio-view' as path_to_portfolio_view %}
{% url 'dbt:dbt-view' as path_to_dbt_view %}
{% url 'tftsd:tftsd-view' as path_to_tftsd_view %}
{% url 'caparu:caparu-view' as path_to_caparu_view %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Tali Rozenman Ismael</title>
        <link rel="stylesheet" type="text/css" href={% static 'style.css' %}/>
    </head>
    <body>
            <button id="btn"> <img src="{% static 'images/tali.png' %}" class="tali"> </button>        
            <nav id="nav">
                <ul>
                    <li><a href="{{path_to_cv_view}}">CV</a></li>
                    <li><a href="{{path_to_portfolio_view}}">Portfolio</a></li>
                    <li><a href="{{path_to_dbt_view}}">don't be trashy</a></li>
                    <li><a href="{{path_to_tftsd_view}}">Tales from the S.D</a></li>
                    <li><a href="{{path_to_caparu_view}}">Caparu</a></li>
                </ul>
            </nav>
        

        {% block content %}
        {% endblock content %}

        {% block scripts %}
        <script type="text/javascript" src={% static 'main.js' %}></script>
        {% endblock scripts %}  
    </body>

templates/main/home.html
{% load static %}
{% url 'cv:cv-view' as path_to_cv_view %}
{% url 'portfolio:portfolio-view' as path_to_portfolio_view %}
{% url 'dbt:dbt-view' as path_to_dbt_view %}
{% url 'tftsd:tftsd-view' as path_to_tftsd_view %}
{% url 'caparu:caparu-view' as path_to_caparu_view %}
{% url 'tali:home-view' as path_to_home_view %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no" />
        <title>Tali Rozenman Ismael</title>
        <link rel="stylesheet" type="text/css" href={% static 'home.css' %}/>
        <!-- semantic UI -->
        <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    </head>
    <body>
        <div>
            <!-- <a href="#" id="btn" class="logo"><img src="tali.png" class="tali"></a> -->
            <button id="btn"> <img src="{% static 'images/tali.png' %}" class="tali"> </button>
        </div>
        <div>
            <nav id="nav">
                <ul>
                    <li><a href="{{path_to_cv_view}}">Tali Rozenman Ismael</a></li>
                    <li><a href="{{path_to_portfolio_view}}">Portfolio</a></li>
                    <li><a href="{{path_to_dbt_view}}">don't be trashy</a></li>
                    <li><a href="{{path_to_tftsd_view}}">Tales from the S.D</a></li>
                    <li><a href="{{path_to_caparu_view}}">Caparu</a></li>
                    <li><a href="{{path_to_home_view}}">Home</a></li>
                </ul>
            </nav>
        </div>

        <script type="text/javascript" src={% static 'home.js' %}></script> 
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>  
    </body>

    <!-- ☰ -->

   
   

</html>

templates/main/navbar.html
{% load static %}
{% url 'cv:cv-view' as path_to_cv_view %}
{% url 'portfolio:portfolio-view' as path_to_portfolio_view %}
{% url 'dbt:dbt-view' as path_to_dbt_view %}
{% url 'tftsd:tftsd-view' as path_to_tftsd_view %}
{% url 'caparu:caparu-view' as path_to_caparu_view %}
{% url 'tali:home-view' as path_to_home_view %}
<body>
    

<button id="btn"> <img src="{% static 'images/tali.png' %}" class="tali"> </button>
<nav id="nav">
    <ul>
        <li><a href="{{path_to_cv_view}}">Tali Rozenman Ismael</a></li>
        <li><a href="{{path_to_portfolio_view}}">Portfolio</a></li>
        <li><a href="{{path_to_dbt_view}}">don't be trashy</a></li>
        <li><a href="{{path_to_tftsd_view}}">Tales from the S.D</a></li>
        <li><a href="{{path_to_caparu_view}}">Caparu</a></li>
        <li><a href="{{path_to_home_view}}">Home</a></li>
    </ul>
</nav>


<script type="text/javascript" src={% static 'main.js' %}></script>
</body>

tftsd/templates/tftsd/tftsd.html
{% extends 'base.html' %}

{% block title %}
Tales from the S.D.
{% endblock title %}

{% block content %}
<section class="center">
    <header class="intro">
        <div class="intro-slideshow">
          <img src="https://www.dropbox.com/s/h8rds5ozk0u3s2f/coder.jpg?raw=1">
          <img src="https://www.dropbox.com/s/lf29ifrd354ngyv/coffee.jpg?raw=1">
          <img src="https://www.dropbox.com/s/lxnf1mxej90qoae/library.jpg?raw=1">
          <img src="https://www.dropbox.com/s/15gdoyzoai94j6j/path.jpg?raw=1">
          <img src="https://www.dropbox.com/s/jk3ulwea2bolurw/universe.jpg?raw=1">
        </div>
        <div class="intro-header">
          <h1>Tales from the S.D.</h1>
          <p>Curated Networking</p>
        </div>
      </header>


</section>

{% endblock content %}